server:
  port: 8002
mybatis:
  type-aliases-package: com.wxx.springCloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 #修改eureka上的默认描述信息 status

#info配置
info:
  app.name: wxx-springcloud-8002
  company.name: blog.xlkj.com：：：一土式样
















